development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:e8eb8e4e3bbe16ea550abff68bf08755@koi.redistogo.com:11668/
  # url: redis://localhost:6379/1
