# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0b9070f5ffa36aa8e772d3e2cc3d389ee36a947c97bb9fea8a1ccbb9d58a47b485d98fb351477cbed455dbf8a4876fe2e24f708aaab4aae61753ef72c13c7903

test:
  secret_key_base: 6f0868919970555e9bb4bd066b8e6198d0bbca2fdde0cfbaa84836e484fba06998074845562edf9a1b678ebd1080aba8c90e36fb9bdf464553673c4528b726c9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

cloud_name: <%= ENV["CLOUDINARY_CLOUD_NAME"] %>
api_key: <%= ENV["CLOUDINARY_API_KEY"] %>
api_secret: <%= ENV["CLOUDINARY_API_SECRET"] %>
enhance_image_tag: true
static_image_support: true
